import * as es from './ast-tree-nodes';

export type ASTTreeNodes =
  | es.ArrayExpression
  | es.ArrayPattern
  | es.ArrowFunctionExpression
  | es.AssignmentExpression
  | es.AssignmentPattern
  | es.AwaitExpression
  | es.BigIntLiteral
  | es.BinaryExpression
  | es.BlockStatement
  | es.BreakStatement
  | es.CallExpression
  | es.CatchClause
  | es.ClassBody
  | es.ClassDeclaration
  | es.ClassExpression
  | es.ClassProperty
  | es.ConditionalExpression
  | es.ContinueStatement
  | es.DebuggerStatement
  | es.Decorator
  | es.DoWhileStatement
  | es.EmptyStatement
  | es.ExportAllDeclaration
  | es.ExportDefaultDeclaration
  | es.ExportNamedDeclaration
  | es.ExportSpecifier
  | es.ExpressionStatement
  | es.ForInStatement
  | es.ForOfStatement
  | es.ForStatement
  | es.FunctionDeclaration
  | es.FunctionExpression
  | es.Identifier
  | es.IfStatement
  | es.Import
  | es.ImportDeclaration
  | es.ImportDefaultSpecifier
  | es.ImportNamespaceSpecifier
  | es.ImportSpecifier
  | es.JSXAttribute
  | es.JSXClosingElement
  | es.JSXClosingFragment
  | es.JSXElement
  | es.JSXEmptyExpression
  | es.JSXExpressionContainer
  | es.JSXFragment
  | es.JSXIdentifier
  | es.JSXMemberExpression
  // | es.JSXNamespacedName // https://github.com/Microsoft/TypeScript/issues/7411
  | es.JSXOpeningElement
  | es.JSXOpeningFragment
  | es.JSXSpreadAttribute
  | es.JSXSpreadChild
  | es.JSXText
  | es.LabeledStatement
  | es.Literal
  | es.LogicalExpression
  | es.MemberExpression
  | es.MetaProperty
  | es.MethodDefinition
  | es.NewExpression
  | es.ObjectExpression
  | es.ObjectPattern
  | es.Program
  | es.Property
  | es.RestElement
  | es.ReturnStatement
  | es.SequenceExpression
  | es.SpreadElement
  | es.Super
  | es.SwitchCase
  | es.SwitchStatement
  | es.TaggedTemplateExpression
  | es.TemplateElement
  | es.TemplateLiteral
  | es.ThisExpression
  | es.ThrowStatement
  | es.TryStatement
  | es.UnaryExpression
  | es.UpdateExpression
  | es.VariableDeclaration
  | es.VariableDeclarator
  | es.WhileStatement
  | es.WithStatement
  | es.YieldExpression
  | es.TSAbstractClassProperty
  // | es.TSAbstractKeyword
  | es.TSAbstractMethodDefinition
  | es.TSAnyKeyword
  | es.TSArrayType
  | es.TSAsExpression
  | es.TSAsyncKeyword
  | es.TSBooleanKeyword
  | es.TSBigIntKeyword
  | es.TSConditionalType
  | es.TSConstructorType
  | es.TSCallSignatureDeclaration
  | es.TSClassImplements
  | es.TSConstructSignatureDeclaration
  // | es.TSDeclareKeyword
  | es.TSDeclareFunction
  | es.TSEnumDeclaration
  | es.TSEnumMember
  | es.TSExportAssignment
  // | es.TSExportKeyword
  | es.TSExternalModuleReference
  | es.TSImportType
  | es.TSInferType
  | es.TSLiteralType
  | es.TSIndexedAccessType
  | es.TSIndexSignature
  | es.TSInterfaceBody
  | es.TSInterfaceDeclaration
  | es.TSInterfaceHeritage
  | es.TSImportEqualsDeclaration
  | es.TSFunctionType
  | es.TSMethodSignature
  | es.TSModuleBlock
  | es.TSModuleDeclaration
  | es.TSNamespaceExportDeclaration
  | es.TSNonNullExpression
  | es.TSNeverKeyword
  | es.TSNullKeyword
  | es.TSNumberKeyword
  | es.TSMappedType
  | es.TSObjectKeyword
  | es.TSParameterProperty
  | es.TSPrivateKeyword
  | es.TSPropertySignature
  | es.TSProtectedKeyword
  | es.TSPublicKeyword
  | es.TSQualifiedName
  // | es.TSQuestionToken
  // | es.TSReadonlyKeyword
  | es.TSRestType
  | es.TSStaticKeyword
  | es.TSStringKeyword
  | es.TSSymbolKeyword
  | es.TSThisType
  | es.TSTypeAnnotation
  | es.TSTypeAliasDeclaration
  | es.TSTypeAssertion
  | es.TSTypeLiteral
  | es.TSTypeOperator
  | es.TSTypeParameter
  | es.TSTypeParameterDeclaration
  | es.TSTypeParameterInstantiation
  | es.TSTypePredicate
  | es.TSTypeReference
  | es.TSTypeQuery
  | es.TSIntersectionType
  | es.TSTupleType
  | es.TSOptionalType
  | es.TSParenthesizedType
  | es.TSUnionType
  | es.TSUndefinedKeyword
  | es.TSUnknownKeyword
  | es.TSVoidKeyword
  // abstract types
  | es.FunctionDeclarationLike
  | es.ClassPropertyLikeNode
  | es.ClassLikeNode
  | es.TSFunctionDeclarationLike
  | es.TSExpressionWithTypeArgumentsLike;
