// THIS CODE WAS AUTOMATICALLY GENERATED
// DO NOT EDIT THIS CODE BY HAND
// RUN THE FOLLOWING COMMAND FROM THE WORKSPACE ROOT TO REGENERATE:
// npx nx generate-lib @typescript-eslint/scope-manager

import type { ImplicitLibVariableOptions } from '../variable';
import { TYPE } from './base-config';

export const dom_iterable = {
  AudioParam: TYPE,
  AudioParamMap: TYPE,
  BaseAudioContext: TYPE,
  CSSKeyframesRule: TYPE,
  CSSRuleList: TYPE,
  CSSStyleDeclaration: TYPE,
  Cache: TYPE,
  CanvasPath: TYPE,
  CanvasPathDrawingStyles: TYPE,
  DOMRectList: TYPE,
  DOMStringList: TYPE,
  DOMTokenList: TYPE,
  DataTransferItemList: TYPE,
  EventCounts: TYPE,
  FileList: TYPE,
  FontFaceSet: TYPE,
  FormData: TYPE,
  HTMLAllCollection: TYPE,
  HTMLCollectionBase: TYPE,
  HTMLCollectionOf: TYPE,
  HTMLFormElement: TYPE,
  HTMLSelectElement: TYPE,
  Headers: TYPE,
  IDBDatabase: TYPE,
  IDBObjectStore: TYPE,
  MIDIInputMap: TYPE,
  MIDIOutput: TYPE,
  MIDIOutputMap: TYPE,
  MediaKeyStatusMap: TYPE,
  MediaList: TYPE,
  MessageEvent: TYPE,
  MimeTypeArray: TYPE,
  NamedNodeMap: TYPE,
  Navigator: TYPE,
  NodeList: TYPE,
  NodeListOf: TYPE,
  Plugin: TYPE,
  PluginArray: TYPE,
  RTCRtpTransceiver: TYPE,
  RTCStatsReport: TYPE,
  SVGLengthList: TYPE,
  SVGNumberList: TYPE,
  SVGPointList: TYPE,
  SVGStringList: TYPE,
  SVGTransformList: TYPE,
  SourceBufferList: TYPE,
  SpeechRecognitionResult: TYPE,
  SpeechRecognitionResultList: TYPE,
  StyleSheetList: TYPE,
  SubtleCrypto: TYPE,
  TextTrackCueList: TYPE,
  TextTrackList: TYPE,
  TouchList: TYPE,
  URLSearchParams: TYPE,
  WEBGL_draw_buffers: TYPE,
  WEBGL_multi_draw: TYPE,
  WebGL2RenderingContextBase: TYPE,
  WebGL2RenderingContextOverloads: TYPE,
  WebGLRenderingContextBase: TYPE,
  WebGLRenderingContextOverloads: TYPE,
} as Record<string, ImplicitLibVariableOptions>;
