// THIS CODE WAS AUTOMATICALLY GENERATED
// DO NOT EDIT THIS CODE BY HAND
// YOU CAN REGENERATE IT USING yarn generate:lib

import { ImplicitLibVariableOptions } from '../variable';
import { es2015_symbol } from './es2015.symbol';

export const es2015_symbol_wellknown = {
  ...es2015_symbol,
  SymbolConstructor: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'SymbolConstructor',
    writeable: false,
  },
  Symbol: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Symbol',
    writeable: false,
  },
  Array: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Array',
    writeable: false,
  },
  Date: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Date',
    writeable: false,
  },
  Map: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Map',
    writeable: false,
  },
  WeakMap: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WeakMap',
    writeable: false,
  },
  Set: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Set',
    writeable: false,
  },
  WeakSet: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WeakSet',
    writeable: false,
  },
  JSON: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'JSON',
    writeable: false,
  },
  Function: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Function',
    writeable: false,
  },
  GeneratorFunction: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'GeneratorFunction',
    writeable: false,
  },
  Math: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Math',
    writeable: false,
  },
  Promise: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Promise',
    writeable: false,
  },
  PromiseConstructor: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PromiseConstructor',
    writeable: false,
  },
  RegExp: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RegExp',
    writeable: false,
  },
  RegExpConstructor: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RegExpConstructor',
    writeable: false,
  },
  String: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'String',
    writeable: false,
  },
  ArrayBuffer: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ArrayBuffer',
    writeable: false,
  },
  DataView: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'DataView',
    writeable: false,
  },
  Int8Array: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Int8Array',
    writeable: false,
  },
  Uint8Array: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Uint8Array',
    writeable: false,
  },
  Uint8ClampedArray: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Uint8ClampedArray',
    writeable: false,
  },
  Int16Array: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Int16Array',
    writeable: false,
  },
  Uint16Array: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Uint16Array',
    writeable: false,
  },
  Int32Array: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Int32Array',
    writeable: false,
  },
  Uint32Array: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Uint32Array',
    writeable: false,
  },
  Float32Array: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Float32Array',
    writeable: false,
  },
  Float64Array: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Float64Array',
    writeable: false,
  },
  ArrayConstructor: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ArrayConstructor',
    writeable: false,
  },
  MapConstructor: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'MapConstructor',
    writeable: false,
  },
  SetConstructor: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'SetConstructor',
    writeable: false,
  },
  ArrayBufferConstructor: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ArrayBufferConstructor',
    writeable: false,
  },
} as Record<string, ImplicitLibVariableOptions>;
