// THIS CODE WAS AUTOMATICALLY GENERATED
// DO NOT EDIT THIS CODE BY HAND
// YOU CAN REGENERATE IT USING yarn generate:lib

import { ImplicitLibVariableOptions } from '../variable';
import { es2015_symbol } from './es2015.symbol';

export const es2015_iterable = {
  ...es2015_symbol,
  SymbolConstructor: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'SymbolConstructor',
  },
  IteratorYieldResult: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IteratorYieldResult',
  },
  IteratorReturnResult: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IteratorReturnResult',
  },
  IteratorResult: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IteratorResult',
  },
  Iterator: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Iterator',
  },
  Iterable: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Iterable',
  },
  IterableIterator: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IterableIterator',
  },
  Array: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Array',
  },
  ArrayConstructor: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ArrayConstructor',
  },
  ReadonlyArray: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ReadonlyArray',
  },
  IArguments: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IArguments',
  },
  Map: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Map',
  },
  ReadonlyMap: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ReadonlyMap',
  },
  MapConstructor: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'MapConstructor',
  },
  WeakMap: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WeakMap',
  },
  WeakMapConstructor: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WeakMapConstructor',
  },
  Set: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Set',
  },
  ReadonlySet: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ReadonlySet',
  },
  SetConstructor: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'SetConstructor',
  },
  WeakSet: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WeakSet',
  },
  WeakSetConstructor: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WeakSetConstructor',
  },
  Promise: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Promise',
  },
  PromiseConstructor: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PromiseConstructor',
  },
  String: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'String',
  },
  Int8Array: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Int8Array',
  },
  Int8ArrayConstructor: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Int8ArrayConstructor',
  },
  Uint8Array: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Uint8Array',
  },
  Uint8ArrayConstructor: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Uint8ArrayConstructor',
  },
  Uint8ClampedArray: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Uint8ClampedArray',
  },
  Uint8ClampedArrayConstructor: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Uint8ClampedArrayConstructor',
  },
  Int16Array: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Int16Array',
  },
  Int16ArrayConstructor: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Int16ArrayConstructor',
  },
  Uint16Array: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Uint16Array',
  },
  Uint16ArrayConstructor: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Uint16ArrayConstructor',
  },
  Int32Array: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Int32Array',
  },
  Int32ArrayConstructor: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Int32ArrayConstructor',
  },
  Uint32Array: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Uint32Array',
  },
  Uint32ArrayConstructor: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Uint32ArrayConstructor',
  },
  Float32Array: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Float32Array',
  },
  Float32ArrayConstructor: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Float32ArrayConstructor',
  },
  Float64Array: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Float64Array',
  },
  Float64ArrayConstructor: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Float64ArrayConstructor',
  },
} as Record<string, ImplicitLibVariableOptions>;
