// THIS CODE WAS AUTOMATICALLY GENERATED
// DO NOT EDIT THIS CODE BY HAND
// YOU CAN REGENERATE IT USING yarn generate:lib

import { ImplicitLibVariableOptions } from '../variable';

export const webworker = {
  AddEventListenerOptions: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'AddEventListenerOptions',
  },
  AesCbcParams: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'AesCbcParams',
  },
  AesCtrParams: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'AesCtrParams',
  },
  AesDerivedKeyParams: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'AesDerivedKeyParams',
  },
  AesGcmParams: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'AesGcmParams',
  },
  AesKeyAlgorithm: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'AesKeyAlgorithm',
  },
  AesKeyGenParams: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'AesKeyGenParams',
  },
  Algorithm: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Algorithm',
  },
  BlobPropertyBag: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'BlobPropertyBag',
  },
  CacheQueryOptions: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CacheQueryOptions',
  },
  CanvasRenderingContext2DSettings: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasRenderingContext2DSettings',
  },
  ClientQueryOptions: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ClientQueryOptions',
  },
  CloseEventInit: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CloseEventInit',
  },
  CryptoKeyPair: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CryptoKeyPair',
  },
  CustomEventInit: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CustomEventInit',
  },
  DOMMatrix2DInit: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'DOMMatrix2DInit',
  },
  DOMMatrixInit: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'DOMMatrixInit',
  },
  DOMPointInit: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'DOMPointInit',
  },
  DOMQuadInit: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'DOMQuadInit',
  },
  DOMRectInit: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'DOMRectInit',
  },
  DevicePermissionDescriptor: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'DevicePermissionDescriptor',
  },
  EcKeyGenParams: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EcKeyGenParams',
  },
  EcKeyImportParams: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EcKeyImportParams',
  },
  EcdhKeyDeriveParams: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EcdhKeyDeriveParams',
  },
  EcdsaParams: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EcdsaParams',
  },
  ErrorEventInit: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ErrorEventInit',
  },
  EventInit: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EventInit',
  },
  EventListenerOptions: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EventListenerOptions',
  },
  EventSourceInit: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EventSourceInit',
  },
  ExtendableEventInit: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ExtendableEventInit',
  },
  ExtendableMessageEventInit: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ExtendableMessageEventInit',
  },
  FetchEventInit: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'FetchEventInit',
  },
  FilePropertyBag: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'FilePropertyBag',
  },
  GetNotificationOptions: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'GetNotificationOptions',
  },
  HkdfParams: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'HkdfParams',
  },
  HmacImportParams: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'HmacImportParams',
  },
  HmacKeyGenParams: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'HmacKeyGenParams',
  },
  IDBIndexParameters: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IDBIndexParameters',
  },
  IDBObjectStoreParameters: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IDBObjectStoreParameters',
  },
  IDBVersionChangeEventInit: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IDBVersionChangeEventInit',
  },
  ImageBitmapOptions: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ImageBitmapOptions',
  },
  ImageBitmapRenderingContextSettings: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ImageBitmapRenderingContextSettings',
  },
  ImageEncodeOptions: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ImageEncodeOptions',
  },
  JsonWebKey: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'JsonWebKey',
  },
  KeyAlgorithm: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'KeyAlgorithm',
  },
  MessageEventInit: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'MessageEventInit',
  },
  MidiPermissionDescriptor: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'MidiPermissionDescriptor',
  },
  MultiCacheQueryOptions: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'MultiCacheQueryOptions',
  },
  NavigationPreloadState: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'NavigationPreloadState',
  },
  NotificationAction: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'NotificationAction',
  },
  NotificationEventInit: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'NotificationEventInit',
  },
  NotificationOptions: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'NotificationOptions',
  },
  Pbkdf2Params: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Pbkdf2Params',
  },
  PerformanceObserverInit: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PerformanceObserverInit',
  },
  PermissionDescriptor: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PermissionDescriptor',
  },
  PipeOptions: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PipeOptions',
  },
  PostMessageOptions: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PostMessageOptions',
  },
  ProgressEventInit: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ProgressEventInit',
  },
  PromiseRejectionEventInit: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PromiseRejectionEventInit',
  },
  PushEventInit: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PushEventInit',
  },
  PushPermissionDescriptor: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PushPermissionDescriptor',
  },
  PushSubscriptionChangeEventInit: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PushSubscriptionChangeEventInit',
  },
  PushSubscriptionJSON: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PushSubscriptionJSON',
  },
  PushSubscriptionOptionsInit: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PushSubscriptionOptionsInit',
  },
  QueuingStrategy: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'QueuingStrategy',
  },
  ReadableStreamReadDoneResult: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ReadableStreamReadDoneResult',
  },
  ReadableStreamReadValueResult: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ReadableStreamReadValueResult',
  },
  RegistrationOptions: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RegistrationOptions',
  },
  RequestInit: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RequestInit',
  },
  ResponseInit: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ResponseInit',
  },
  RsaHashedImportParams: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RsaHashedImportParams',
  },
  RsaHashedKeyGenParams: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RsaHashedKeyGenParams',
  },
  RsaKeyGenParams: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RsaKeyGenParams',
  },
  RsaOaepParams: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RsaOaepParams',
  },
  RsaOtherPrimesInfo: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RsaOtherPrimesInfo',
  },
  RsaPssParams: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RsaPssParams',
  },
  StorageEstimate: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'StorageEstimate',
  },
  SyncEventInit: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'SyncEventInit',
  },
  TextDecodeOptions: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'TextDecodeOptions',
  },
  TextDecoderOptions: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'TextDecoderOptions',
  },
  TextEncoderEncodeIntoResult: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'TextEncoderEncodeIntoResult',
  },
  Transformer: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Transformer',
  },
  UnderlyingByteSource: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'UnderlyingByteSource',
  },
  UnderlyingSink: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'UnderlyingSink',
  },
  UnderlyingSource: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'UnderlyingSource',
  },
  WebGLContextAttributes: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WebGLContextAttributes',
  },
  WebGLContextEventInit: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WebGLContextEventInit',
  },
  WorkerOptions: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WorkerOptions',
  },
  EventListener: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EventListener',
  },
  ANGLE_instanced_arrays: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ANGLE_instanced_arrays',
  },
  AbortController: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'AbortController',
  },
  AbortSignalEventMap: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'AbortSignalEventMap',
  },
  AbortSignal: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'AbortSignal',
  },
  AbstractWorkerEventMap: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'AbstractWorkerEventMap',
  },
  AbstractWorker: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'AbstractWorker',
  },
  AesCfbParams: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'AesCfbParams',
  },
  AesCmacParams: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'AesCmacParams',
  },
  AnimationFrameProvider: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'AnimationFrameProvider',
  },
  Blob: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Blob',
  },
  Body: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Body',
  },
  BroadcastChannelEventMap: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'BroadcastChannelEventMap',
  },
  BroadcastChannel: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'BroadcastChannel',
  },
  ByteLengthQueuingStrategy: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ByteLengthQueuingStrategy',
  },
  Cache: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Cache',
  },
  CacheStorage: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'CacheStorage',
  },
  CanvasCompositing: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasCompositing',
  },
  CanvasDrawImage: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasDrawImage',
  },
  CanvasDrawPath: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasDrawPath',
  },
  CanvasFillStrokeStyles: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasFillStrokeStyles',
  },
  CanvasFilters: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasFilters',
  },
  CanvasGradient: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'CanvasGradient',
  },
  CanvasImageData: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasImageData',
  },
  CanvasImageSmoothing: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasImageSmoothing',
  },
  CanvasPath: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasPath',
  },
  CanvasPathDrawingStyles: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasPathDrawingStyles',
  },
  CanvasPattern: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'CanvasPattern',
  },
  CanvasRect: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasRect',
  },
  CanvasShadowStyles: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasShadowStyles',
  },
  CanvasState: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasState',
  },
  CanvasText: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasText',
  },
  CanvasTextDrawingStyles: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasTextDrawingStyles',
  },
  CanvasTransform: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasTransform',
  },
  Client: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Client',
  },
  Clients: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Clients',
  },
  CloseEvent: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'CloseEvent',
  },
  ConcatParams: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ConcatParams',
  },
  CountQueuingStrategy: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'CountQueuingStrategy',
  },
  Crypto: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Crypto',
  },
  CryptoKey: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'CryptoKey',
  },
  CustomEvent: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'CustomEvent',
  },
  DOMException: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'DOMException',
  },
  DOMMatrix: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'DOMMatrix',
  },
  DOMMatrixReadOnly: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'DOMMatrixReadOnly',
  },
  DOMPoint: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'DOMPoint',
  },
  DOMPointReadOnly: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'DOMPointReadOnly',
  },
  DOMQuad: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'DOMQuad',
  },
  DOMRect: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'DOMRect',
  },
  DOMRectReadOnly: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'DOMRectReadOnly',
  },
  DOMStringList: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'DOMStringList',
  },
  DedicatedWorkerGlobalScopeEventMap: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'DedicatedWorkerGlobalScopeEventMap',
  },
  DedicatedWorkerGlobalScope: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'DedicatedWorkerGlobalScope',
  },
  DhImportKeyParams: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'DhImportKeyParams',
  },
  DhKeyAlgorithm: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'DhKeyAlgorithm',
  },
  DhKeyDeriveParams: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'DhKeyDeriveParams',
  },
  DhKeyGenParams: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'DhKeyGenParams',
  },
  EXT_blend_minmax: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EXT_blend_minmax',
  },
  EXT_frag_depth: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EXT_frag_depth',
  },
  EXT_sRGB: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EXT_sRGB',
  },
  EXT_shader_texture_lod: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EXT_shader_texture_lod',
  },
  EXT_texture_filter_anisotropic: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EXT_texture_filter_anisotropic',
  },
  ErrorEvent: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ErrorEvent',
  },
  Event: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Event',
  },
  EventListenerObject: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EventListenerObject',
  },
  EventSourceEventMap: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EventSourceEventMap',
  },
  EventSource: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'EventSource',
  },
  EventTarget: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'EventTarget',
  },
  ExtendableEvent: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ExtendableEvent',
  },
  ExtendableMessageEvent: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ExtendableMessageEvent',
  },
  FetchEvent: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'FetchEvent',
  },
  File: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'File',
  },
  FileList: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'FileList',
  },
  FileReaderEventMap: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'FileReaderEventMap',
  },
  FileReader: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'FileReader',
  },
  FileReaderSync: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'FileReaderSync',
  },
  FormData: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'FormData',
  },
  GenericTransformStream: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'GenericTransformStream',
  },
  Headers: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Headers',
  },
  IDBArrayKey: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IDBArrayKey',
  },
  IDBCursor: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'IDBCursor',
  },
  IDBCursorWithValue: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'IDBCursorWithValue',
  },
  IDBDatabaseEventMap: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IDBDatabaseEventMap',
  },
  IDBDatabase: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'IDBDatabase',
  },
  IDBFactory: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'IDBFactory',
  },
  IDBIndex: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'IDBIndex',
  },
  IDBKeyRange: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'IDBKeyRange',
  },
  IDBObjectStore: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'IDBObjectStore',
  },
  IDBOpenDBRequestEventMap: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IDBOpenDBRequestEventMap',
  },
  IDBOpenDBRequest: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'IDBOpenDBRequest',
  },
  IDBRequestEventMap: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IDBRequestEventMap',
  },
  IDBRequest: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'IDBRequest',
  },
  IDBTransactionEventMap: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IDBTransactionEventMap',
  },
  IDBTransaction: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'IDBTransaction',
  },
  IDBVersionChangeEvent: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'IDBVersionChangeEvent',
  },
  ImageBitmap: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ImageBitmap',
  },
  ImageBitmapRenderingContext: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ImageBitmapRenderingContext',
  },
  ImageData: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ImageData',
  },
  MessageChannel: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'MessageChannel',
  },
  MessageEvent: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'MessageEvent',
  },
  MessagePortEventMap: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'MessagePortEventMap',
  },
  MessagePort: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'MessagePort',
  },
  NavigationPreloadManager: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'NavigationPreloadManager',
  },
  NavigatorConcurrentHardware: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'NavigatorConcurrentHardware',
  },
  NavigatorID: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'NavigatorID',
  },
  NavigatorLanguage: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'NavigatorLanguage',
  },
  NavigatorOnLine: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'NavigatorOnLine',
  },
  NavigatorStorage: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'NavigatorStorage',
  },
  NotificationEventMap: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'NotificationEventMap',
  },
  Notification: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Notification',
  },
  NotificationEvent: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'NotificationEvent',
  },
  OES_element_index_uint: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'OES_element_index_uint',
  },
  OES_standard_derivatives: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'OES_standard_derivatives',
  },
  OES_texture_float: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'OES_texture_float',
  },
  OES_texture_float_linear: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'OES_texture_float_linear',
  },
  OES_texture_half_float: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'OES_texture_half_float',
  },
  OES_texture_half_float_linear: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'OES_texture_half_float_linear',
  },
  OES_vertex_array_object: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'OES_vertex_array_object',
  },
  OffscreenCanvas: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'OffscreenCanvas',
  },
  OffscreenCanvasRenderingContext2D: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'OffscreenCanvasRenderingContext2D',
  },
  Path2D: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Path2D',
  },
  PerformanceEventMap: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PerformanceEventMap',
  },
  Performance: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Performance',
  },
  PerformanceEntry: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'PerformanceEntry',
  },
  PerformanceMark: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'PerformanceMark',
  },
  PerformanceMeasure: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'PerformanceMeasure',
  },
  PerformanceObserver: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'PerformanceObserver',
  },
  PerformanceObserverEntryList: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'PerformanceObserverEntryList',
  },
  PerformanceResourceTiming: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'PerformanceResourceTiming',
  },
  PermissionStatusEventMap: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PermissionStatusEventMap',
  },
  PermissionStatus: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'PermissionStatus',
  },
  Permissions: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Permissions',
  },
  ProgressEvent: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ProgressEvent',
  },
  PromiseRejectionEvent: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'PromiseRejectionEvent',
  },
  PushEvent: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'PushEvent',
  },
  PushManager: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'PushManager',
  },
  PushMessageData: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'PushMessageData',
  },
  PushSubscription: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'PushSubscription',
  },
  PushSubscriptionChangeEvent: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'PushSubscriptionChangeEvent',
  },
  PushSubscriptionOptions: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'PushSubscriptionOptions',
  },
  ReadableByteStreamController: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ReadableByteStreamController',
  },
  ReadableStream: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ReadableStream',
  },
  ReadableStreamBYOBReader: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ReadableStreamBYOBReader',
  },
  ReadableStreamBYOBRequest: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ReadableStreamBYOBRequest',
  },
  ReadableStreamDefaultController: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ReadableStreamDefaultController',
  },
  ReadableStreamDefaultReader: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ReadableStreamDefaultReader',
  },
  ReadableStreamReader: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ReadableStreamReader',
  },
  Request: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Request',
  },
  Response: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Response',
  },
  ServiceWorkerEventMap: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ServiceWorkerEventMap',
  },
  ServiceWorker: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ServiceWorker',
  },
  ServiceWorkerContainerEventMap: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ServiceWorkerContainerEventMap',
  },
  ServiceWorkerContainer: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ServiceWorkerContainer',
  },
  ServiceWorkerGlobalScopeEventMap: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ServiceWorkerGlobalScopeEventMap',
  },
  ServiceWorkerGlobalScope: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ServiceWorkerGlobalScope',
  },
  ServiceWorkerRegistrationEventMap: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ServiceWorkerRegistrationEventMap',
  },
  ServiceWorkerRegistration: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ServiceWorkerRegistration',
  },
  SharedWorker: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'SharedWorker',
  },
  SharedWorkerGlobalScopeEventMap: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'SharedWorkerGlobalScopeEventMap',
  },
  SharedWorkerGlobalScope: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'SharedWorkerGlobalScope',
  },
  StorageManager: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'StorageManager',
  },
  SubtleCrypto: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'SubtleCrypto',
  },
  SyncEvent: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'SyncEvent',
  },
  SyncManager: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'SyncManager',
  },
  TextDecoder: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'TextDecoder',
  },
  TextDecoderCommon: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'TextDecoderCommon',
  },
  TextDecoderStream: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'TextDecoderStream',
  },
  TextEncoder: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'TextEncoder',
  },
  TextEncoderCommon: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'TextEncoderCommon',
  },
  TextEncoderStream: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'TextEncoderStream',
  },
  TextMetrics: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'TextMetrics',
  },
  TransformStream: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'TransformStream',
  },
  TransformStreamDefaultController: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'TransformStreamDefaultController',
  },
  URL: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'URL',
  },
  URLSearchParams: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'URLSearchParams',
  },
  WEBGL_color_buffer_float: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WEBGL_color_buffer_float',
  },
  WEBGL_compressed_texture_astc: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WEBGL_compressed_texture_astc',
  },
  WEBGL_compressed_texture_s3tc: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WEBGL_compressed_texture_s3tc',
  },
  WEBGL_compressed_texture_s3tc_srgb: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WEBGL_compressed_texture_s3tc_srgb',
  },
  WEBGL_debug_renderer_info: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WEBGL_debug_renderer_info',
  },
  WEBGL_debug_shaders: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WEBGL_debug_shaders',
  },
  WEBGL_depth_texture: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WEBGL_depth_texture',
  },
  WEBGL_draw_buffers: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WEBGL_draw_buffers',
  },
  WEBGL_lose_context: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WEBGL_lose_context',
  },
  WebGL2RenderingContext: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGL2RenderingContext',
  },
  WebGL2RenderingContextBase: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WebGL2RenderingContextBase',
  },
  WebGL2RenderingContextOverloads: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WebGL2RenderingContextOverloads',
  },
  WebGLActiveInfo: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLActiveInfo',
  },
  WebGLBuffer: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLBuffer',
  },
  WebGLContextEvent: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLContextEvent',
  },
  WebGLFramebuffer: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLFramebuffer',
  },
  WebGLObject: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLObject',
  },
  WebGLProgram: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLProgram',
  },
  WebGLQuery: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLQuery',
  },
  WebGLRenderbuffer: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLRenderbuffer',
  },
  WebGLRenderingContext: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLRenderingContext',
  },
  WebGLRenderingContextBase: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WebGLRenderingContextBase',
  },
  WebGLRenderingContextOverloads: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WebGLRenderingContextOverloads',
  },
  WebGLSampler: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLSampler',
  },
  WebGLShader: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLShader',
  },
  WebGLShaderPrecisionFormat: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLShaderPrecisionFormat',
  },
  WebGLSync: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLSync',
  },
  WebGLTexture: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLTexture',
  },
  WebGLTransformFeedback: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLTransformFeedback',
  },
  WebGLUniformLocation: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLUniformLocation',
  },
  WebGLVertexArrayObject: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLVertexArrayObject',
  },
  WebGLVertexArrayObjectOES: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WebGLVertexArrayObjectOES',
  },
  WebSocketEventMap: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WebSocketEventMap',
  },
  WebSocket: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebSocket',
  },
  WindowClient: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WindowClient',
  },
  WindowOrWorkerGlobalScope: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WindowOrWorkerGlobalScope',
  },
  WorkerEventMap: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WorkerEventMap',
  },
  Worker: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Worker',
  },
  WorkerGlobalScopeEventMap: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WorkerGlobalScopeEventMap',
  },
  WorkerGlobalScope: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WorkerGlobalScope',
  },
  WorkerLocation: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WorkerLocation',
  },
  WorkerNavigator: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WorkerNavigator',
  },
  WritableStream: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WritableStream',
  },
  WritableStreamDefaultController: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WritableStreamDefaultController',
  },
  WritableStreamDefaultWriter: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WritableStreamDefaultWriter',
  },
  XMLHttpRequestEventMap: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'XMLHttpRequestEventMap',
  },
  XMLHttpRequest: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'XMLHttpRequest',
  },
  XMLHttpRequestEventTargetEventMap: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'XMLHttpRequestEventTargetEventMap',
  },
  XMLHttpRequestEventTarget: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'XMLHttpRequestEventTarget',
  },
  XMLHttpRequestUpload: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'XMLHttpRequestUpload',
  },
  EventListenerOrEventListenerObject: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EventListenerOrEventListenerObject',
  },
  Console: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Console',
  },
  WebAssembly: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebAssembly',
  },
  FrameRequestCallback: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'FrameRequestCallback',
  },
  OnErrorEventHandlerNonNull: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'OnErrorEventHandlerNonNull',
  },
  PerformanceObserverCallback: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PerformanceObserverCallback',
  },
  QueuingStrategySizeCallback: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'QueuingStrategySizeCallback',
  },
  ReadableByteStreamControllerCallback: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ReadableByteStreamControllerCallback',
  },
  ReadableStreamDefaultControllerCallback: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ReadableStreamDefaultControllerCallback',
  },
  ReadableStreamErrorCallback: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ReadableStreamErrorCallback',
  },
  TransformStreamDefaultControllerCallback: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'TransformStreamDefaultControllerCallback',
  },
  TransformStreamDefaultControllerTransformCallback: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'TransformStreamDefaultControllerTransformCallback',
  },
  VoidFunction: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'VoidFunction',
  },
  WritableStreamDefaultControllerCloseCallback: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WritableStreamDefaultControllerCloseCallback',
  },
  WritableStreamDefaultControllerStartCallback: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WritableStreamDefaultControllerStartCallback',
  },
  WritableStreamDefaultControllerWriteCallback: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WritableStreamDefaultControllerWriteCallback',
  },
  WritableStreamErrorCallback: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WritableStreamErrorCallback',
  },
  HeadersInit: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'HeadersInit',
  },
  BodyInit: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'BodyInit',
  },
  RequestInfo: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RequestInfo',
  },
  BlobPart: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'BlobPart',
  },
  DOMHighResTimeStamp: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'DOMHighResTimeStamp',
  },
  CanvasImageSource: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasImageSource',
  },
  OffscreenRenderingContext: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'OffscreenRenderingContext',
  },
  MessageEventSource: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'MessageEventSource',
  },
  ImageBitmapSource: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ImageBitmapSource',
  },
  OnErrorEventHandler: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'OnErrorEventHandler',
  },
  TimerHandler: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'TimerHandler',
  },
  PerformanceEntryList: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PerformanceEntryList',
  },
  PushMessageDataInit: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PushMessageDataInit',
  },
  ReadableStreamReadResult: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ReadableStreamReadResult',
  },
  VibratePattern: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'VibratePattern',
  },
  AlgorithmIdentifier: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'AlgorithmIdentifier',
  },
  HashAlgorithmIdentifier: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'HashAlgorithmIdentifier',
  },
  BigInteger: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'BigInteger',
  },
  NamedCurve: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'NamedCurve',
  },
  GLenum: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'GLenum',
  },
  GLboolean: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'GLboolean',
  },
  GLbitfield: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'GLbitfield',
  },
  GLint: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'GLint',
  },
  GLsizei: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'GLsizei',
  },
  GLintptr: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'GLintptr',
  },
  GLsizeiptr: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'GLsizeiptr',
  },
  GLuint: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'GLuint',
  },
  GLfloat: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'GLfloat',
  },
  GLclampf: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'GLclampf',
  },
  TexImageSource: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'TexImageSource',
  },
  Float32List: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Float32List',
  },
  Int32List: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Int32List',
  },
  GLint64: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'GLint64',
  },
  GLuint64: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'GLuint64',
  },
  Uint32List: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Uint32List',
  },
  BufferSource: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'BufferSource',
  },
  DOMTimeStamp: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'DOMTimeStamp',
  },
  FormDataEntryValue: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'FormDataEntryValue',
  },
  IDBValidKey: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IDBValidKey',
  },
  Transferable: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Transferable',
  },
  BinaryType: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'BinaryType',
  },
  CanvasDirection: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasDirection',
  },
  CanvasFillRule: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasFillRule',
  },
  CanvasLineCap: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasLineCap',
  },
  CanvasLineJoin: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasLineJoin',
  },
  CanvasTextAlign: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasTextAlign',
  },
  CanvasTextBaseline: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasTextBaseline',
  },
  ClientTypes: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ClientTypes',
  },
  ColorSpaceConversion: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ColorSpaceConversion',
  },
  EndingType: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EndingType',
  },
  FrameType: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'FrameType',
  },
  IDBCursorDirection: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IDBCursorDirection',
  },
  IDBRequestReadyState: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IDBRequestReadyState',
  },
  IDBTransactionMode: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IDBTransactionMode',
  },
  ImageOrientation: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ImageOrientation',
  },
  ImageSmoothingQuality: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ImageSmoothingQuality',
  },
  KeyFormat: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'KeyFormat',
  },
  KeyType: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'KeyType',
  },
  KeyUsage: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'KeyUsage',
  },
  NotificationDirection: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'NotificationDirection',
  },
  NotificationPermission: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'NotificationPermission',
  },
  OffscreenRenderingContextId: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'OffscreenRenderingContextId',
  },
  PermissionName: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PermissionName',
  },
  PermissionState: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PermissionState',
  },
  PremultiplyAlpha: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PremultiplyAlpha',
  },
  PushEncryptionKeyName: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PushEncryptionKeyName',
  },
  PushPermissionState: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PushPermissionState',
  },
  ReferrerPolicy: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ReferrerPolicy',
  },
  RequestCache: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RequestCache',
  },
  RequestCredentials: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RequestCredentials',
  },
  RequestDestination: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RequestDestination',
  },
  RequestMode: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RequestMode',
  },
  RequestRedirect: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RequestRedirect',
  },
  ResizeQuality: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ResizeQuality',
  },
  ResponseType: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ResponseType',
  },
  ServiceWorkerState: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ServiceWorkerState',
  },
  ServiceWorkerUpdateViaCache: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ServiceWorkerUpdateViaCache',
  },
  VisibilityState: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'VisibilityState',
  },
  WebGLPowerPreference: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WebGLPowerPreference',
  },
  WorkerType: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WorkerType',
  },
  XMLHttpRequestResponseType: {
    eslintImplicitGlobalSetting: 'readonly',
    isTypeVariable: true,
    isValueVariable: false,
    name: 'XMLHttpRequestResponseType',
  },
} as Record<string, ImplicitLibVariableOptions>;
