version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    ignore:
      - dependency-name: cypress
    schedule:
      interval: weekly
      day: monday

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    ignore:
      - dependency-name: cypress
