comment:
  footer: Please do not respond to this message. Thanks! 💖
  header: 🤖 Beep boop, hello!

labels:
  - name: formatting
    labeled:
      issue:
        body: |
          I'm the ⚡ TypeScript ESLint Formatting Bot ⚡, and I'm popping in automatically to advertise that we **strongly recommend against using ESLint rules for formatting purposes**.

          See our **[What About Formatting? docs page](https://typescript-eslint.io/docs/linting/troubleshooting/formatting)** for more info.

          This message is automated and serves only as a reminder. We will still triage your issue and, as long as it only involves fixing existing formatting rules, do not plan on automatically closing it.
