replies:
  - body: |
      👋 Hey @{{ author }}! Just checking in, is this still something you have time for? No worries if not - I just don't want to leave it hanging.
    name: Checking In
  - body: |
      Thanks for posting! This is a duplicate of #<insert issue>. Before filing an issue, please [use our issue search](https://github.com/typescript-eslint/typescript-eslint/issues) to check for open and closed issues that already address what you're looking for.
    name: Clearly Duplicate Issue
  - body: |
      Thanks for the issue!
      \
      This is an extension rule. That means we take the base rule and extend it to support TS syntax or features.
      \
      We don't break from the base rule to add new features unless they are specifically related to TS.
      \
      In this instance — this request is not related to TS, thus we shall not implement it. If you'd like to see it, feel free to raise a request with the ESLint team.
      \
    name: Extension Rule - Reject Due to Enhancement
  - body: |
      The fix has been merged to main, and will be released Monday, as per our [release schedule](https://typescript-eslint.io/users/releases/#latest)
      \
      If you need it sooner, please try the `canary` tag on NPM.
    name: Fix Has Been Merged
  - body: |
      👋 thanks for sending this over @{{ author }}!
      \
      > ```md\
      > - [] Steps in Contributing were taken\
      > ```\
      \
      We ask that people file issues for non-trivial changes like this one for a few reasons:\
      \
      * The templates ask reporters to provide info we'd need to triage requests, including a full reproduction - which is also useful if we later have to spelunk through the repository's history\
      * We want to raise visibility for the changes to let folks have a chance to discuss nuances before work is done\
      * Even if you're at the 'expert' level where specifically you know to check for duplicates and understand the codebase well enough to make these changes, most users aren't - so it sets a negative precedent\
      \
      Could you please [file an issue](https://github.com/typescript-eslint/typescript-eslint/issues/new/choose) explaining why you'd like this?\
    name: Needs Issue
  - body: |
      Thanks for the report @<reporter>!\
      This might be a valid issue, but we can't tell because you haven't filled in enough information.\
      Please fill in the rest of the issue template so we can take a look.\
      Thanks!
    name: Needs More Info
  - body: |
      Thanks for the report @<reporter>!\
      I can't reproduce the issue using the repository you provided.\
      Could you please comment with instructions on how to reproduce the issue?\
      Thanks!
    name: Needs Full Reproduction
  - body: |
      Thanks for the report @<reporter>!\
      I can't reproduce the issue using the code you provided.\
      Could you please create an isolated reproduction in our playground (https://typescript-eslint.io/play) and comment back when you've got one?\
      We prefer an isolated reproduction so that we as volunteer maintainers can quickly reproduce the issue and more easily find the cause.\
      Thanks!
    name: Needs Playground Reproduction
  - body: |
      With any issue opened in this project — it either has visible progress in the form of an attached PR, or it has no progress.\
      \
      We are a community-run project. The volunteer maintainers spend most of their time triaging issues and reviewing PRs. This means that most issues will not progress unless a member of the community steps up and champions it.\
      \
      If this issue is important to you — consider being that champion.\
      \
      If not — please just subscribe to the issue and wait patiently.\
      Commenting asking for status updates does not bump issue priority in any way and just serves to spam everyone subscribed to the issue.
    name: Progress - Blunt
  - body: |
      We are a community run project. The **volunteer** maintainers spend most of their time triaging issues and reviewing PRs. This means that most issues *will not progress* unless a member of the community steps up and **champions** it.
      \
      If this issue is important to you — consider being that champion.
      If not — please use the subscribe function and wait patiently for someone else to implement this.
    name: Progress - Nice
  - body: |
      Closing this issue as it's been stale for ~6 weeks without activity. Feel free to reopen @{{ author }} if you have time - but no worries if not! If anybody wants to drive it forward, please do either post here or in a new issue with the info we asked about. Thanks! 😊
    name: Pruning Stale Issue
  - body: |
      Closing this PR as it's been stale for ~6 weeks without activity. Feel free to reopen @{{ author }} if you have time - but no worries if not! If anybody wants to drive it forward, please do post your own PR - and if you use this as a start, consider adding `Co-authored-by: @{{ author }}` at the end of your PR description. Thanks! 😊
    name: Pruning Stale PR
  - body: |
      As per [our contributing guidelines](https://typescript-eslint.io/contributing/pull-requests#addressing-feedback-and-beyond) this PR is in the queue of PRs to reviewed, and will be reviewed when we are able.
      \
      This project is run by volunteer maintainers, so it might be a bit before we can find the time to get to it.
    name: Review Queue
  - body: |
      We ***STRONGLY*** recommend you use automatic code formatters like [prettier](https://www.npmjs.com/package/prettier).
      \
      Stylistic lint rules take a lot of effort to write, require ongoing maintenance to add more configuration as people want to fit their preferences, and are a large burden to maintain as new syntax is added.
      The configurability also leads to huge fanout [making tests huge, and awful to maintain](https://github.com/typescript-eslint/typescript-eslint/blob/b814e635c1f34139c89e0176727480935dd45cac/packages/eslint-plugin/tests/rules/type-annotation-spacing.test.ts).
      \
      It's for these reasons that [eslint has frozen all stylistic lint rule options, and will not accept any new ones](https://eslint.org/blog/2020/05/changes-to-rules-policies).
      See also our [What About Formatting?](https://typescript-eslint.io/linting/troubleshooting/formatting) docs.
    name: Use Prettier
