replies:
  - body: |
      Thanks for posting! This is a duplicate of #<insert issue>. Before filing an issue, please [use our issue search](https://github.com/typescript-eslint/typescript-eslint/issues) to check for open and closed issues that already address what you're looking for.
    name: Clearly Duplicate Issue
  - body: |
      With any issue in opened in this project - it either has a visible progress in the form of an attached PR, or it has no progress.\
      \
      We are a community run project. The volunteer maintainers spend most of their time triaging issues and reviewing PRs. This means that most issues will not progress unless a member of the community steps up and champions it.\
      \
      If this issue is important to you - consider being that champion.\
      \
      If not - please just subscribe to the issue and wait patiently.\
      Commenting asking for status updates does not bump issue priority in any way and just serves to spam everyone subscribed to the issue.
    name: Bump for Updates
