replies:
  - body: |
      <img alt="Maury meme: You checked 'I have searched for related issues'. A cursory issue search related issues determined that was a lie." src="https://user-images.githubusercontent.com/3335181/186501430-7f4c481a-f557-48b0-826c-74bb8434f4d5.png" height="483" width="488">\
      Dup of #<insert issue>. Next time, please use the search 🙂.
    name: Clearly Duplicate Issue
