codecov:
  token: 36f54445-cf11-44dc-b17f-182451b8f60e
coverage:
  status:
    patch:
      default:
        target: 90%
    project:
      default:
        target: auto
        threshold: 2%
comment:
  layout: diff, flags, files
  require_changes: true
  
