codecov:
  require_ci_to_pass: no
  notify:
    wait_for_ci: no

coverage:
  status:
    patch:
      default:
        target: 90%
    project:
      default:
        target: auto
        threshold: 2%

comment:
  layout: diff, flags, files
  require_changes: true
