language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '11'
  - '10'
  - '9'
  - '8'
  - '6'
install:
  - yarn --ignore-engines
script:
  - commitlint-travis
  - yarn check-format
  - yarn test
  - yarn build
  - yarn global add codecov
after_success:
  - codecov
branches:
  only:
    - master
