language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '11'
  - '10'
  - '9'
  - '8'
  - '6'
install:
  - yarn --ignore-engines
script:
  # TODO: Reenable after migrations are complete
  # - commitlint-travis
  - yarn check-format
  - yarn workspace eslint-plugin-typescript docs:check
  - yarn build
  - yarn test
  # TODO: Reimplement automated integration-tests from typescript-eslint-parser
  # for the monorepo, after the migrations are complete
  # yarn integration-tests
  - yarn global add codecov
after_success:
  - codecov
branches:
  only:
    - master
