sudo: required
services:
  - docker
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '11'
  - '10'
  - '8'
  - '6'
install:
  # This also runs a build as part of the postinstall
  # bootstrap
  - yarn --ignore-engines --frozen-lockfile
script:
  # TODO: Fix this check
  # - yarn workspace eslint-plugin docs:check
  - yarn test
  - yarn global add codecov
after_success:
  - codecov
branches:
  only:
    - master

jobs:
  include:
    - stage: Code and Commit Formatting and Integration Tests
      node_js: "11"
      script:
        - commitlint-travis
        - yarn check-format
        - yarn integration-tests
