packages:
  - packages/*

catalog:
  '@eslint/js': ^10.0.0
  '@types/babel__code-frame': ^7.0.6
  '@types/mdast': ^4.0.4
  '@types/natural-compare': ^1.4.3
  '@types/node': ^22.19.3
  '@types/react': ^18.3.21
  '@vitest/coverage-v8': ^4.0.18
  '@vitest/pretty-format': ^4.0.18
  '@vitest/utils': ^4.0.18
  ajv: ^6.12.6
  eslint: ^10.0.0
  esquery: ^1.7.0
  glob: ^11.1.0
  globals: ^16.5.0
  json-schema: ^0.4.0
  mdast-util-from-markdown: ^2.0.2
  mdast-util-mdx: ^3.0.0
  prettier: 3.8.0
  rimraf: ^5.0.10
  tsx: ^4.7.2
  typescript: '>=4.8.4 <6.0.0'
  vitest: ^4.0.18
  yaml: ^2.8.2

catalogMode: strict
