packages:
  - packages/*

catalog:
  "@vitest/coverage-v8": "^3.2.4"
  "@eslint/js": "^10.0.0"
  "@types/natural-compare": "^1.4.3"
  "@types/node": "^22.19.3"
  "@types/react": ^18.3.21
  eslint: "^10.0.0"
  esquery: "^1.7.0"
  glob: "^11.1.0"
  globals: "^16.5.0"
  json-schema: "^0.4.0"
  rimraf: "^5.0.10"
  tsx: "^4.7.2"
  typescript: ">=4.8.4 <6.0.0"
  vitest: "^3.2.4"
