name: "🐛 Report a Bug With a Rule"
description: "Report a bug you encountered with a lint rule"
title: "Bug: [rule name here] <short description of the issue>"
labels:
  - bug
  - "package: eslint-plugin"
  - triage
body:
  - type: checkboxes
    id: sanity-checks
    attributes:
      label: Before You File a Bug Report Please Confirm You Have Done The Following...
      description: If any of these required steps are not taken, we may not be able to review your issue. Help us to help you!
      options:
        - label: I have tried restarting my IDE and the issue persists.
          required: true
        - label: I have updated to the latest version of the packages.
          required: true
        - label: I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
          required: true
        - label: I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.
          required: true
  - type: input
    id: playground-link
    attributes:
      label: Playground Link
      description: |
        Link to an isolated reproduction [in our online playground](https://typescript-eslint.io/play/).
        If either of the following holds true:
        - You can't reproduce the issue in the playground
        - Your issue requires some complex setup - such as multiple files or a specific folder structure.

        ***Please do not use this template.*** Instead, select the
        ["Report a complex bug you encountered by providing an isolated reproduction repository" template](https://github.com/typescript-eslint/typescript-eslint/issues/new?template=08-bug-report-complex.yaml).
        ***Help us to help you!***
      placeholder: https://typescript-eslint.io/play/...
    validations:
      required: true
  - type: textarea
    id: repro-code
    attributes:
      label: Repro Code
      description: A ***minimal*** code sample which reproduces the issue
      render: typescript
    validations:
      required: true
  - type: textarea
    id: eslint-config
    attributes:
      label: ESLint Config
      description: |
        A ***minimal*** ESLint config for reproducing the issue.
        Please do not just paste your entire ESLint config - it just makes it harder for us to investigate.
        If this is more than around 30 lines and/or contains lint rule settings unrelated to your bug report, you probably haven't isolated the repro.
        ***Help us to help you!***
      render: javascript
      value: |
        module.exports = {
          parser: "@typescript-eslint/parser",
          rules: {
            "@typescript-eslint/<rule-name>": ["error", ...<options>],
          },
        };
    validations:
      required: true
  - type: textarea
    id: typescript-config
    attributes:
      label: tsconfig
      description: (Optional) A ***minimal*** tsconfig for reproducing the issue, if you're using type-aware linting
      render: jsonc
      value: |
        {
          "compilerOptions": {
            // ...
          }
        }
  - type: textarea
    id: expected
    attributes:
      label: Expected Result
      description: What did you expect to happen? Please be specific here - list the exact lines and messages you expect.
      placeholder: I expected that the 3rd line should report the error "foo bar"...
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Result
      description: What actually happened? Please be specific here - list the exact lines and messages that caused errors.
      placeholder: There was no error on the 3rd line...
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Info
      description: |
        Any additional info you'd like to provide.
        If ESLint threw an exception, please run your lint again with the `--debug` flag, and dump the output below. e.g. `eslint path/to/broken/file.ts --debug`
  - type: textarea
    id: versions
    attributes:
      label: Versions
      value: |
        | package                                | version |
        | -------------------------------------- | ------- |
        | `@typescript-eslint/eslint-plugin`     | `X.Y.Z` |
        | `@typescript-eslint/parser`            | `X.Y.Z` |
        | `TypeScript`                           | `X.Y.Z` |
        | `ESLint`                               | `X.Y.Z` |
        | `node`                                 | `X.Y.Z` |
    validations:
      required: true
