name: '🐛 Complex Bug With a Reproduction'
description: Report a complex bug with an isolated reproduction
title: 'Bug: <short description of the issue>'
labels:
  - bug
  - triage
body:
  - type: markdown
    attributes:
      value: |
        An isolated reproduction is one we can clone locally and get running without other projects or existing knowledge of your project. If we cannot reproduce your bug quickly with the provided steps, we may not be able to take action on this issue. Help us to help you!
  - type: checkboxes
    id: preliminary-checks
    attributes:
      label: Before You File a Bug Report Please Confirm You Have Done The Following...
      description: If any of these required steps are not taken, we may not be able to review your issue. Help us to help you!
      options:
        - label: I have tried restarting my IDE and the issue persists.
          required: true
        - label: I have updated to the latest version of the packages.
          required: true
        - label: I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
          required: true
        - label: I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.
          required: true
  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Tell us exactly what went wrong and what to look for. Please be as specific as possible here.
      placeholder: I expected that the file X should report the error "foo bar"...
    validations:
      required: true
  - type: input
    id: repro-repo
    attributes:
      label: Reproduction Repository Link
      description: Link to an isolated reproduction repository on GitHub
      placeholder: https://github.com/your-username/repro-repo
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Repro Steps
      description: The steps we need to take to reproduce the bug using your repro
      value: |
        1) clone the repo
        2) `yarn install`
        3) `yarn lint`
    validations:
      required: true
  - type: textarea
    id: versions
    attributes:
      label: Versions
      value: |
        <!-- Fill in the relevant versions and delete the others -->
        | package                                | version |
        | -------------------------------------- | ------- |
        | `@typescript-eslint/eslint-plugin`     | `X.Y.Z` |
        | `@typescript-eslint/parser`            | `X.Y.Z` |
        | `@typescript-eslint/scope-manager`     | `X.Y.Z` |
        | `@typescript-eslint/typescript-estree` | `X.Y.Z` |
        | `@typescript-eslint/type-utils`        | `X.Y.Z` |
        | `@typescript-eslint/utils`             | `X.Y.Z` |
        | `TypeScript`                           | `X.Y.Z` |
        | `ESLint`                               | `X.Y.Z` |
        | `node`                                 | `X.Y.Z` |
    validations:
      required: true
