name: Documentation request
description: Request a change in documentation
title: "Docs: "
labels:
  - documentation
  - triage
body:
  - type: markdown
    attributes:
      value: |
        Before opening a new issue:
        - Read through [typescript-eslint.io](https://typescript-eslint.io)
        - Look for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=label%3Adocumentation)
        - If your request is for help, not documentation, please ask on [StackOverflow](https://stackoverflow.com/questions/tagged/typescript-eslint)
  - type: textarea
    attributes:
      label: Suggested Changes
      description: What would you like to see happen in the docs?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Affected URL(s)
      description: Which URL(s) on the website does this CRUD?
    validations:
      required: true
