name: Rule proposal
description: "Propose a new rule for the '@typescript-eslint/eslint-plugin' package"
title: "Rule proposal: "
labels:
  - "enhancement: new base rule extension"
  - "package: eslint-plugin"
  - triage
body:
  - type: markdown
    attributes:
      value: |
        Before opening a new issue:
        - Look for existing [open or closed rule proposals](https://github.com/typescript-eslint/typescript-eslint/issues?q=label%3A%22enhancement%3A+new+base+rule+extension%22)
        - Look for [existing rules](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin)
        - Ensure that the rule you want to propose is related to types. If not, consider looking into [eslint-plugin-unicorn](https://github.com/sindresorhus/eslint-plugin-unicorn)
  - type: textarea
    validations:
      required: true
    attributes:
      label: Description
      description: Explain here why this rule would be beneficial
  - type: textarea
    validations:
      required: true
    attributes:
      label: Fail
      description: Specify an example of code that should be detected
      value: |
        ```ts
        var replace = 'me';
        ```
  - type: textarea
    validations:
      required: true
    attributes:
      label: Pass
      description: Specify an example of code that would be accepted in its place
      value: |
        ```ts
        const replace = 'me';
        ```
