# IMPORTANT NOTE TO MAINTAINERS
#
# Changes to this composite action should be carefully considered and reviewed because it is referenced
# and executed by multiple workflows in our private-automations repository.
#
# Ensure that a member of @typescript-eslint/core-team tests changes there before merging.

name: 'Prepare: Install'
description: 'Prepares the repo by installing dependencies'
inputs:
  node-version:
    description: 'The node version to setup'
    required: true
  registry-url:
    description: 'Define registry-url'
    required: false
  # NOTE: This is required for our use-case of sharing this action across multiple repos
  working-directory:
    description: 'Override the working directory to run the installation in'
    required: false
    default: '.'

# outputs: - no outputs

runs:
  using: 'composite'
  steps:
    - name: echo github.ref
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: echo ${{ github.ref }}

    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        cache: 'pnpm'
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        pnpm install --frozen-lockfile
        pnpm run check-clean-workspace-after-install
      env:
        # Other environment variables
        HUSKY: '0' # By default do not run HUSKY install
        SKIP_POSTINSTALL: 'true'
