name: 'Prepare: Checkout and Install'
description: 'Prepares the repo for a job by checking out and installing dependencies'
inputs:
  node-version:
    description: 'The node version to setup'
    required: true
  registry-url:
    description: 'Define registry-url'
    required: false

# outputs: - no outputs

runs:
  using: 'composite'
  steps:
    - name: echo github.ref
      shell: bash
      run: echo ${{ github.ref }}

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}

    - name: Get yarn cache directory path
      shell: bash
      id: yarn-cache-dir-path
      run: echo "yarn_cache_dir=$(yarn cache dir)" >> $GITHUB_ENV

    - uses: actions/cache@v3
      id: yarn-cache
      with:
        path: |
          ${{ env.yarn_cache_dir }}
          ~/.cache/Cypress
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    # if the cache was hit - this will run in <1s
    - name: Install dependencies
      shell: bash
      run: |
        yarn --ignore-engines --frozen-lockfile --ignore-scripts
        yarn check-clean-workspace-after-install
        yarn patch-package
