name: "Prepare: Checkout and Install"
description: "Prepares the repo for a job by checking out and installing dependencies"
inputs:
  node-version:
    description: "The node version to setup"
    required: true
  registry-url:
    description: "Define registry-url"
    required: false
  typescript-version:
    description: "A modified TypeScript version to setup"
    required: false

# outputs: - no outputs

runs:
  using: "composite"
  steps:
    - name: echo github.ref
      shell: bash
      run: echo ${{ github.ref }}

    - if: ${{ inputs.typescript-version != null }}
      run: |
        cat package.json | awk '{sub(/typescript\":\ \"[0-9.]+/,"typescript\": \"${{ inputs.typescript-version }}")}1' > package.tmp.json
        cp package.tmp.json package.json
      shell: bash
      name: Set TypeScript resolution to ${{ inputs.typescript-version }}

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}

    - name: Get yarn cache directory path
      shell: bash
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v3
      id: yarn-cache
      with:
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          ~/.cache/Cypress
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('package.json') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    # if the cache was hit - this will run in <1s
    - name: Install dependencies
      shell: bash
      run: |
        yarn --ignore-engines --frozen-lockfile --ignore-scripts
        yarn check-clean-workspace-after-install
