declare module 'eslint-utils' {
  export const findVariable: unknown;
  export const getFunctionHeadLocation: unknown;
  export const getFunctionNameWithKind: unknown;
  export const getInnermostScope: unknown;
  export const getPropertyName: unknown;
  export const getStaticValue: unknown;
  export const getStringIfConstant: unknown;
  export const hasSideEffect: unknown;
  export const isArrowToken: unknown;
  export const isClosingBraceToken: unknown;
  export const isClosingBracketToken: unknown;
  export const isClosingParenToken: unknown;
  export const isColonToken: unknown;
  export const isCommaToken: unknown;
  export const isCommentToken: unknown;
  export const isNotArrowToken: unknown;
  export const isNotClosingBraceToken: unknown;
  export const isNotClosingBracketToken: unknown;
  export const isNotClosingParenToken: unknown;
  export const isNotColonToken: unknown;
  export const isNotCommaToken: unknown;
  export const isNotCommentToken: unknown;
  export const isNotOpeningBraceToken: unknown;
  export const isNotOpeningBracketToken: unknown;
  export const isNotOpeningParenToken: unknown;
  export const isNotSemicolonToken: unknown;
  export const isOpeningBraceToken: unknown;
  export const isOpeningBracketToken: unknown;
  export const isOpeningParenToken: unknown;
  export const isParenthesized: unknown;
  export const isSemicolonToken: unknown;
  export const PatternMatcher: unknown;
  export const ReferenceTracker: {
    READ: never;
    CALL: never;
    CONSTRUCT: never;
    new (): never;
  };
}
