# This workflow is used on the rare occassion we need to manually cut a release.
# It can be triggered via the Github UI or the Github API.

name: Manual publish to Github Releases and NPM

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Check out as an admin to allow for pushing back to master
        token: ${{ secrets.JAMES_HENRY_GH_TOKEN }}
        # Check out the branch that was specified as part of the trigger
        ref: ${{ github.ref }}
        # We need to fetch all tags and branches
        fetch-depth: 0

    - name: Verify head of master hasn't changed
      run: |
        # We ensure that the latest commit on master is still the one we expected when
        # we started the release job, otherwise we exit
        if [ "$GITHUB_SHA" != "$(git rev-parse --verify HEAD)" ]; then
            echo "ERROR: The commit SHA at the HEAD of master has changed"
            echo "Expected: $GITHUB_SHA"
            echo "Actual: $(git rev-parse --verify HEAD)"
            exit 1;
        fi

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: |
        yarn --ignore-engines --frozen-lockfile --ignore-scripts
        yarn lerna:init
        yarn check:clean-workspace-after-install

    - name: Run build
      run: |
        yarn build

    - name: Determine what version to release and publish to Github (--yes skips the confirmation prompt)
      run: |
        # Required for github release to work
        git config user.name 'James Henry'
        git config user.email 'james@henry.sc'

        GH_TOKEN=${{ secrets.JAMES_HENRY_GH_TOKEN }} npx lerna version --loglevel=silly --yes --conventional-commits --exact --force-publish --github-release -m "chore: publish %s"

    - name: Publish the updated versions to NPM (--yes skips the confirmation prompt)
      run: npx lerna publish from-package --yes
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
