name: Test Against Versions

on:
  push:
    branches:
      - typescript-5.1-testing
  pull_request:
    branches:
      - typescript-5.1-testing

env:
  PRIMARY_NODE_VERSION: 18
  # Only set the read-write token if we are on the main branch
  NX_CLOUD_ACCESS_TOKEN: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') && secrets.NX_CLOUD_ACCESS_TOKEN || '' }}

defaults:
  run:
    shell: bash

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    name: Build All Packages
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: ./.github/actions/prepare-install
        with:
          node-version: ${{ env.PRIMARY_NODE_VERSION }}
      - name: Build
        uses: ./.github/actions/prepare-build

  unit_tests:
    name: Run Unit Tests
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ['typescript-estree']
    env:
      # Added the - at the end to function as a separator to improve readability in the PR comment from the Nx cloud app
      NX_CLOUD_ENV_NAME: 'Node 18 Testing -'
      COLLECT_COVERAGE: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install
        uses: ./.github/actions/prepare-install
        with:
          node-version: 18
      - name: Build
        uses: ./.github/actions/prepare-build
      - name: Run unit tests for Node 18
        run: npx nx test ${{ matrix.package }} --coverage=false parse.moduleResolver
        env:
          CI: true
